package convert

var MIDINames []string = []string{
	// Piano
	"Acoustic Grand Piano",
	"Bright Acoustic Piano",
	"Electric Grand Piano",
	"Honky-tonk Piano",
	"Electric Piano 1",
	"Electric Piano 2",
	"Harpsichord",
	"Clavinet",

	// Chromatic Percussion
	"Celesta",
	"Glockenspiel",
	"Music Box",
	"Vibraphone",
	"Marimba",
	"Xylophone",
	"Tubular Bells",
	"Dulcimer",

	// Organ
	"Drawbar Organ",
	"Percussive Organ",
	"Rock Organ",
	"Church Organ",
	"Reed Organ",
	"Accordion",
	"Harmonica",
	"Tango Accordion",

	// Guitar
	"Acoustic Guitar nylon",
	"Acoustic Guitar steel",
	"Electric Guitar jazz",
	"Electric Guitar clean",
	"Electric Guitar muted",
	"Overdriven Guitar",
	"Distortion Guitar",
	"Guitar harmonics",

	// Bass
	"Acoustic Bass",
	"Electric Bass finger",
	"Electric Bass pick",
	"Fretless Bass",
	"Slap Bass 1",
	"Slap Bass 2",
	"Synth Bass 1",
	"Synth Bass 2",

	// Strings
	"Violin",
	"Viola",
	"Cello",
	"Contrabass",
	"Tremolo Strings",
	"Pizzicato Strings",
	"Orchestral Harp",
	"Timpani",

	// Strings continued
	"String Ensemble 1",
	"String Ensemble 2",
	"Synth Strings 1",
	"Synth Strings 2",
	"Choir Aahs",
	"Voice Oohs",
	"Synth Voice",
	"Orchestra Hit",

	// Brass
	"Trumpet",
	"Trombone",
	"Tuba",
	"Muted Trumpet",
	"French Horn",
	"Brass Section",
	"Synth Brass 1",
	"Synth Brass 2",

	// Reed
	"Soprano Sax",
	"Alto Sax",
	"Tenor Sax",
	"Baritone Sax",
	"Oboe",
	"English Horn",
	"Bassoon",
	"Clarinet",

	// Pipe
	"Piccolo",
	"Flute",
	"Recorder",
	"Pan Flute",
	"Blown Bottle",
	"Shakuhachi",
	"Whistle",
	"Ocarina",

	// Synth Lead
	"Lead 1 square",
	"Lead 2 sawtooth",
	"Lead 3 calliope",
	"Lead 4 chiff",
	"Lead 5 charang",
	"Lead 6 voice",
	"Lead 7 fifths",
	"Lead 8 bass lead",

	// Synth Pad
	"Pad 1 new age",
	"Pad 2 warm",
	"Pad 3 polysynth",
	"Pad 4 choir",
	"Pad 5 bowed",
	"Pad 6 metallic",
	"Pad 7 halo",
	"Pad 8 sweep",

	// Synth Effects
	"FX 1 rain",
	"FX 2 soundtrack",
	"FX 3 crystal",
	"FX 4 atmosphere",
	"FX 5 brightness",
	"FX 6 goblins",
	"FX 7 echoes",
	"FX 8 sci fi",

	// Ethnic
	"Sitar",
	"Banjo",
	"Shamisen",
	"Koto",
	"Kalimba",
	"Bag pipe",
	"Fiddle",
	"Shanai",

	// Percussive
	"Tinkle Bell",
	"Agogo",
	"Steel Drums",
	"Woodblock",
	"Taiko Drum",
	"Melodic Tom",
	"Synth Drum",

	// Sound effects
	"Reverse Cymbal",
	"Guitar Fret Noise",
	"Breath Noise",
	"Seashore",
	"Bird Tweet",
	"Telephone Ring",
	"Helicopter",
	"Applause",
	"Gunshot",
}

var PercussionNames = []string{
	"Percussion 01",
	"Percussion 02",
	"Percussion 03",
	"Percussion 04",
	"Percussion 05",
	"Percussion 06",
	"Percussion 07",
	"Percussion 08",
	"Percussion 09",
	"Percussion 10",
	"Percussion 11",
	"Percussion 12",
	"Percussion 13",
	"Percussion 14",
	"Percussion 15",
	"Percussion 16",
	"Percussion 17",
	"Percussion 18",
	"Percussion 19",
	"Percussion 20",
	"Percussion 21",
	"Percussion 22",
	"Percussion 23",
	"Percussion 24",
	"Percussion 25",
	"Percussion 26",
	"Laser",
	"Whip",
	"Scratch Push",
	"Scratch Pull",
	"Stick Click",
	"Metronome Click",
	"Percussion 33",
	"Metronome Bell",
	"Bass Drum",
	"Kick Drum",
	"Snare Cross Stick",
	"Snare Drum",
	"Hand Clap",
	"Electric Snare Drum",
	"Floor Tom 2",
	"Hi Hat Closed",
	"Floor Tom 1",
	"Hi Hat Foot",
	"Low Tom",
	"Hi Hat Open",
	"Low Mid Tom",
	"High Mid Tom",
	"Crash Cymbal",
	"High Tom",
	"Ride Cymbal",
	"China Cymbal",
	"Ride Bell",
	"Tambourine",
	"Splash cymbal",
	"Cowbell",
	"Crash Cymbal 2",
	"Vibraslap",
	"Ride Cymbal 2",
	"High Bongo",
	"Low Bongo",
	"Conga Dead Stroke",
	"Conga",
	"Tumba",
	"High Timbale",
	"Low Timbale",
	"High Agogo",
	"Low Agogo",
	"Cabasa",
	"Maracas",
	"Whistle Short",
	"Whistle Long",
	"Guiro Short",
	"Guiro Long",
	"Claves",
	"High Woodblock",
	"Low Woodblock",
	"Cuica High",
	"Cuica Low",
	"Triangle Mute",
	"Triangle Open",
	"Shaker",
	"Sleigh Bell",
	"Bell Tree",
	"Castanets",
	"Surdu Dead Stroke",
	"Surdu",
	"Percussion 88",
	"Percussion 89",
	"Percussion 90",
	"Snare Drum Rod",
	"Ocean Drum",
	"Snare Drum Brush",
}
